authors:
  linxinji:
    name: 林欣稷        # 作者姓名
    description: Blogger  # 作者描述
    avatar: ./authors/assets/linxinji.jpg    # 作者头像
    slug: linxinji     # 作者个人资料slug
    url: https://linxinji.github.io/Cultivation-Between-Realms/           # 作者网站URL
  squidfunk:
    name: Martin Donath
    description: Creator
    avatar: https://github.com/squidfunk.png
    url: https://squidfunk.github.io/mkdocs-material/
    slug: squidfunk